### ISSUE TITLE
Connect ESP32 to a Serial Data port to Receive from the DSP

### ISSUE THREAD

**Issue by jjloud** [freeDSP/freeDSP-aurora#1]
The ESP32 is connected to the ADAU1452 in one direction only. The ESP32 can only send data to the DSP, the DSP can not send data to the ESP32. It's worth while to connect the ESP32 to also receive data from the DSP. This would enable the device to be a Bluetooth Source (in addition to what it is now being a "Sink"). It also adds the possibility of it to become a Bluetooth/Wifi "Transceiver" so you can send audio data to a receiving device. 

Just something to think about. Thank you for your hard work on this project.

**Comment by dspverden** [comment]
There are no pins free on the ESP32 that could be used for this.
