### ISSUE TITLE
v2.2.1: 4FIRs + display: presets are incorrectly displayed

### ISSUE THREAD

**Issue by zas** [freeDSP/freeDSP-aurora#102]
The issue was introduced by https://github.com/freeDSP/freeDSP-aurora/commit/dd2ac3b2a3ca8c657b8e869bfa71a93c1e78027e

![IMG_20211212_161500_crop](https://user-images.githubusercontent.com/151042/145849565-ea8c7766-d2f2-49d7-96fe-c6feb197fdc3.jpg)

Issue appeared with preset as string, when it was a letter before, related code: https://github.com/freeDSP/freeDSP-aurora/blob/681eaee9fcaf23816395fc31fa001ef69c9ea5c2/SOURCES/WEBAPP/ESP32/aurora/OLED128x64_SH1106.cpp#L89-L111

**Comment by dspverden** [comment]
Fixed by 853c33e
