### ISSUE TITLE
v2.2.1 PEQs ignored after power off

### ISSUE THREAD

**Issue by pillepalle1234** [freeDSP/freeDSP-aurora#107]
After installing Firmware v2.2.1 my DSPs ignore my PEQs after disconnecting the power. Strangely this does not occur after every power disconnect, i checked the serial monitor during testing and the problem seemed to have disappeared. 
1 day after i reinstalled the DSPs into the case again this issue reappears. Once it is there, the problem persists after consecutive power offs.
The values still show up in the gui but are ignored until I bypass and enable them once again.
This is independant of the used plugin, i have one DSP with the 7.1 and one with the 8 channel plugin.
Shelf-Filters and master volume still seem to work as expected.
I did not import a preset and tried reinstalling firmware/plugin several times.

Here is the log file:
![DSP 2 vergisst einstellungen](https://user-images.githubusercontent.com/86108306/149665000-11a50036-a90a-4c29-b0f6-28d3895d78da.png)

**Comment by dspverden** [comment]
I think I found the reason for this behaviour. Fixing it now.
