### ISSUE TITLE
v2.2.1 DSP creates 2 Acess Points

### ISSUE THREAD

**Issue by pillepalle1234** [freeDSP/freeDSP-aurora#108]
One of my DSPs creates 2 Acess Points. Reinstalling the firmware and plugin did not solve this. It is not critical like my other issue with ignored PEQs but it is there...
![DSP 1](https://user-images.githubusercontent.com/86108306/149665112-94eb7f4e-abe0-485a-b278-d82b56a9d00b.png)

**Comment by dspverden** [comment]
Please, can you check wether other devices show the two access points, too? E.g. what does your phone see?

**Comment by pillepalle1234** [comment]
Thanks for your answer!

The other DSP does not, but appearently your tip with using the phone is golden.
It only shows 1 access point.
So it seems to be a problem with the wifi config of my computer...

**Comment by dspverden** [comment]
Ok, great. Then I will close this, because it seems not related to Aurora DSP.
