### ISSUE TITLE
full amplitude output

### ISSUE THREAD

**Issue by notanumba** [freeDSP/freeDSP-aurora#11]
concerns: auverdionControl 1.2.1 and firmware 1.2.1 with 8 Channel Plugin

Hi,
i am using the above fw and control on Win10 64bit on a Laptop. I logged into the DSP-AccessPoint via wifi. I configured the DSP for some time successfully. 

To my setup:
I am using selfmade 3-way speakers w/o any passive filter network - the DSP works as pre-amp for 6x170W power amplifiers and then on the 2x3 chassis (SUB, MID, HIGH). I am aware of the fact, that its critical for the chassis if something in the pathway goes wrong, but i used resistors until i was sure the setup works flawless. I had it nicely running for some weeks now. And a little tweek should be done today - bad idea: i fried (literally burned) my tweeter :( 

It seems the DSP has a problem with the following situation:

- boot system on laptop
- start auverdionControl 1.2.1
- connect to the DSP
- make some settings - maybe even save them to the board - everything works
- (!) let the laptop go to sleep / hibernate with open auverdionControl
- (eventually switch off/on the DSP - i cant remember doing it)
- wake the laptop - auverdionControl should offer to read the DSP settings (green arrows upper right)
- click the green arrows
- the DSP outputs maximum noise and it seems nonfiltered (low frequencies on all outputs, and on tweeter)

I am not very familiar with the board now, but here is my opinion: 
The DSP got confused in this - for sure dumb - scenario. But anyways - the dsp or auverdioncontrol should realize this, to prevent damage.

1st priority for further development should be a safe usage while playing with the settings. If i am too blind and set something wrong (e.g. lowpass for tweeter) it`s my own stupidity. But the DSP should never play with wrong settings which happened in my case.

Suggestion:
- Before changing any setting in the DSP, volume for the affected chan to -80dB
- If there is no ACK from DSP -> Errormsg
- Write parameters to DSP and Double check data consistency in auverdioncontrol and the DSP
- If there is no consistency -> volume for all chan to -80dB, Errormsg
- Any other safety mechanism (watchdog for DSP?) should be prioritized in development

... out for buying new tweeters....  

notanumba

EDIT 1:
After trying to access the DSP aofter power down / power up with the control utility, it took very long to read out all parameters of the  8 Channel Plugin (approx 4 minutes). I tried to write a previously saved file, and got errors (not an ACK from DSP) and got stuck. Trying to rewrite fw via webota now.

EDIT 2:
BTW: I am sure the noise was self generated by the DSP itself - no signal in Analog1/2 was inserted in the 8 Channel Plugin.

Edit 3:
Instead of Cinema Plugin mentioned in earlier post version i used the default  8 Channel plugin

**Comment by dspverden** [comment]
Firmware version v2.0.0 introduces some consistency checks.

Raphael
