### ISSUE TITLE
Broken display visualization

### ISSUE THREAD

**Issue by exislow** [freeDSP/freeDSP-aurora#115]
Please see https://github.com/freeDSP/freeDSP-aurora/commit/dd2ac3b2a3ca8c657b8e869bfa71a93c1e78027e#r61780025

**Comment by dspverden** [comment]
Are you running v2.2.1?

Plz update to v2.2.2, there it should be solved.

**Comment by exislow** [comment]
Yes, I do. Okay, I will try. But 2.2.2 is still alpha, right?

**Comment by dspverden** [comment]
Did you test it with 2.2.2 (which is now a stable release)?

**Comment by exislow** [comment]
Just tried it: Issue is fixed by v2.2.2. Big thanks!!
