### ISSUE TITLE
Status of ADAT

### ISSUE THREAD

**Issue by Zadagu** [freeDSP/freeDSP-aurora#12]
Hi Raphael,

thanks for your awesome work. I've a question regarding the status of the ADAT interface. Is it already working? Because when i'll look in the XMOS directory I see no related sources.

Thanks,
Zadagu

**Comment by dspverden** [comment]
Hi,

the source codes for the ADAT are part of the XMOS framework. Therefore, you don't see it. You have to enable ADAT in the firmware of course. Then it is working.

Raphael
