### ISSUE TITLE
7.1 Plugin: highpass instead of lowpass filter

### ISSUE THREAD

**Issue by pillepalle1234** [freeDSP/freeDSP-aurora#120]
In the 7.1 plugin there is a lowpass instead of a highpass filter in the Subwoofer section.

While both filters might be useful, a highpass filter is needed in 99% of cases, even closed box subs profit from one 10hz and below when used for movies to limit unnecessary excursion. 
Ported subs can´t be used without a highpass safely when listening at louder volumes.

Most consumer AV-receivers already apply a lowpass filter to the LFE and the rerouted low frequencies from speakers are lowpass filtered already.

I would like to make my own plugin but the script does not work for me, as i already mentioned in the diy-hifi-forum..

Thanks.

**Comment by dspverden** [comment]
I have send you a modified plugin already weeks ago. Does it work now?

**Comment by pillepalle1234** [comment]
Hi,
yes it works flawlessly, thank you :)

**Comment by dspverden** [comment]
Great, would you mind to share it with other Aurora users? E.g. open a GitHub repository for it?

**Comment by pillepalle1234** [comment]
Here it is: https://github.com/pillepalle1234/FreeDSP-Aurora-7.1-Homecinema-Plugin-Highpass

**Comment by dspverden** [comment]
Excellent, thanks!
