### ISSUE TITLE
Missing XMOS source files

### ISSUE THREAD

**Issue by fabianmuehlberger** [freeDSP/freeDSP-aurora#121]
I don't know if it is intentional, but there is no main.c in the XMOS/src/core folder. Also, if the customdefines.h file is made by Ross Owen, XMOS Limited, please refer to the original source. A dedicated readme or Github wiki page would be helpful.

**Comment by dspverden** [comment]
Not sure wether you read the manuals, but you need to download the USB Audio 2 framework from XMOS first and setup the environment as described in the manual.
The framework cannot be hosted in this repository due to legal stuff.

**Comment by fabianmuehlberger** [comment]
I use XTC Tools for programming, XMOS seems to have stopped the development of its xTimeComposer, and I tend to use the newer tools they provide. According to the XTC Tools documentation, the MCU can be programmed with a "C-like" language using lib_xcore and they provide a minimal "hello-world" example written in C. That's the reason I asked and assumed there should be a main.c file to compile your code.

**Comment by dspverden** [comment]
Well the main.c is part of the UAC2 framework. The aurora repository only contains the files the have to be added or have changes. As I said XMOS does not allow to host their framework. Therefore, you first have to download the framework, then add the aurora stuff to it.
