### ISSUE TITLE
S/PDIF Input Settings per Preset

### ISSUE THREAD

**Issue by exislow** [freeDSP/freeDSP-aurora#127]
I have noticed, that these S/PDIF settings are not stored per preset but globally. 

<img width="229" alt="Bildschirmfoto 2022-10-23 um 15 50 41" src="https://user-images.githubusercontent.com/6794066/197396023-94a50f63-1db2-4811-be5a-f6d9ada9c498.png">

This means, I can have only one saved setting, which will be used for all presets. Is there a reason for it? I would be very happy, if S/PDIF settings could also be stored per preset.

**Comment by dspverden** [comment]
Because the other 50% of all users want it not to be stored in the presets. ;-)

**Comment by exislow** [comment]
Haha got it. Is it maybe possible to have an additional option, which declares the S/PDIF globally stored or per preset?

**Comment by dspverden** [comment]
Should be doable.

**Comment by dspverden** [comment]
Oh, I shall make it?
I am planning the next release mid/end December. I think it can come with that release.

**Comment by exislow** [comment]
If it just a "few minutes" work for you, I would really appreciate it. Otherwise I will try to have a look by myself.

**Comment by dspverden** [comment]
I have put it on my ToDo-list now.

**Comment by exislow** [comment]
Thank you very much, this is very kind of you.

Btw.. This totally does not make sense: https://github.com/freeDSP/freeDSP-aurora/issues/127#issuecomment-1288131869

If you could store the S/PDIF settings per preset, then somebody, who likes it, how it is implement currently simply sets the S/PDIF settings in the upcomming implementation in all presets to the same value. Hence, he has the same result as right now with the global setting: S/PDIF input / output is the same for all presets.

Thus, I wouldn't vote for another option which can decalre S/PDIF settings "global" or "per preset" instead I would save time on this and simply make the S/PDIF settings stored per preset, which can be configured to also have the exact same result as with the current implementation. What do you think?

**Comment by dspverden** [comment]
A long time I was thinking like you. But unfortunately life isn't that easy. I did that what you suggest with an another parameter (I think it was the master volume) and got then tons of emails like: "Found a bug, master volume not working when switching preset, please fix it within 24h else my lawyer will send you a nice letter." ;)

**Comment by exislow** [comment]
You are kidding me? Okay, unfortunately I am not much into these legal details but I am sure you will find a safe way. Sorry to hear, that you have made such negative encounters.

**Comment by dspverden** [comment]
Well, I can tell you stories, you won't believe how some go crazy

**Comment by exislow** [comment]
I guess this issue is obsolete, since this behavior is already implemented. I do not know what did not workout with my setup, while I was testing this initially. Sometimes the esp32 is answering the AJAX calls verrrrrryyyyyyyyyyy sloooooow, thus the page is stuck for some seconds with settings from the previously chosen preset. Maybe this was the case.

Since I have tested it again right now and must say, S/PDIF input is already stored per preset. Hence, no actions needed. Sorry for the hassle.
