### ISSUE TITLE
2.0.3 Volume Poti ohne Funktion im Plugin homecinema71

### ISSUE THREAD

**Issue by MarkusGrimm1985** [freeDSP/freeDSP-aurora#15]
Hallo,

leider geht bei mir das Volume Poti im homecinema71 Plugin nicht. Ich habe die neuste Version aufgespielt (2.0.3). Das Poti an sich ist aber richtig verdrahtet und funktioniert auch mit dem Plugin 8channels.

Könnten Sie es bitte im homecinema71 korrigieren?.

Vielen Dank

Gruß

Markus Grimm

**Comment by dspverden** [comment]
Issue was solved by this commit: https://github.com/freeDSP/freeDSP-aurora/commit/c5d38029231cb52ebaf799e99435eace9d63dbb0
