### ISSUE TITLE
aurora.ino:handlePostInputJson: Invalid use of http code 404 in case of failed deserialization 

### ISSUE THREAD

**Issue by zas** [freeDSP/freeDSP-aurora#19]
https://github.com/freeDSP/freeDSP-aurora/blob/21276bfe22873ccbef2ed4d0ad9af257ecf8831c/SOURCES/WEBAPP/ESP32/aurora/aurora.ino#L1862

Imho, it would be more appropriate to use http error code 400 with a meaningful message, perhaps something like.

```
request->send( 400, "text/plain", err.c_str());
```

**Comment by zas** [comment]
Same issue at https://github.com/freeDSP/freeDSP-aurora/blob/21276bfe22873ccbef2ed4d0ad9af257ecf8831c/SOURCES/WEBAPP/ESP32/aurora/aurora.ino#L1932
https://github.com/freeDSP/freeDSP-aurora/blob/21276bfe22873ccbef2ed4d0ad9af257ecf8831c/SOURCES/WEBAPP/ESP32/aurora/aurora.ino#L2037
https://github.com/freeDSP/freeDSP-aurora/blob/21276bfe22873ccbef2ed4d0ad9af257ecf8831c/SOURCES/WEBAPP/ESP32/aurora/aurora.ino#L2145

**Comment by zas** [comment]
Related code doesn't exist anymore in develop branch, so closing.

**Comment by dspverden** [comment]
Fixed here: f833d43
