### ISSUE TITLE
DSP control App

### ISSUE THREAD

**Issue by mincequi** [freeDSP/freeDSP-aurora#2]
Hi there,

i came across your interesting project and i would like to share something i developed for my personal usage.
I realized a software based DSP which can be remote controlled via app (via Bluetooth LE). This is already up and running and you might have a look: https://play.google.com/store/apps/details?id=org.cornrow.corocomo

This app is implemented using Qt and i have iOS, Android, Linux and OSX ports available. Potentially, i might support your hardware as well and we can join up forces here.
What do you think?

Looking forward to hear about your thoughts.

Best regards,
Manuel Weichselbaumer

**Comment by dspverden** [comment]
Hi Manuel,

sorry for my very late response. I decided not to support Bluetooth per default, due to the high licensing costs. So with Bluetooth your are on your own. Sorry.

Raphael
