### ISSUE TITLE
Documentation: User Manual EN 2.1.0: page 20, potentiometer, rotary encoder, etc.

### ISSUE THREAD

**Issue by zas** [freeDSP/freeDSP-aurora#31]
Those sections describe external devices that can be connected.

Examples should be in the same section as the connector description.

**Comment by zas** [comment]
Same goes for Power Supply connection, it should be made clear which kind of power supply is expected (7V, single output + expected power)

**Comment by dspverden** [comment]
Ahm, both requests are already done in user manual 2.1.0. Even with links to successful used modules.

**Comment by zas** [comment]
> Ahm, both requests are already done in user manual 2.1.0. Even with links to successful used modules.

Yes, I based my intial comment on previous doc, then saw you added them, so I modified it, perhaps you read initial version before modification.

Currently, we have a description of each connector, then a section with examples, I think about following structure:

- device1 (e.g. potentiometer)
  - connector description
  - compatible device description
  - examples of devices known to work
- device2 (e.g rotary encoder)
  - etc.

**Comment by mike811** [comment]
Hi,
Page 19 of current German 2.1.0 manual: "Wenn Du ein I2C-Display anschließen möchtest, schließe es bitte ebenfalls an diese Stiftleiste an."
Users may connect their display to Vin (7-12V) according to this.

**Comment by dspverden** [comment]
Fixed the typo on page 19: 89b92949f60f382ca76765154c1b1950259f8080
