### ISSUE TITLE
Documentation: User Manual EN 2.1.0: page 41, make clear 3.3V refers to logic levels

### ISSUE THREAD

**Issue by zas** [freeDSP/freeDSP-aurora#32]
Many USB2Serial devices provide 5V and 3.3V, but still only have 5V TTL logic levels (this is misleading), so make it clear Aurora requires 3.3V logic levels (power is'nt connected anyway)

**Comment by dspverden** [comment]
Fixed here: 2fdda929ab346bdfab28eb38788bc423972b683e
