### ISSUE TITLE
Addon B board B has schematics as PDF, board A has none

### ISSUE THREAD

**Issue by zas** [freeDSP/freeDSP-aurora#38]
https://github.com/freeDSP/freeDSP-aurora/tree/develop/ADDONS/AddOnB/KICAD/Board%20A
https://github.com/freeDSP/freeDSP-aurora/blob/develop/ADDONS/AddOnB/KICAD/Board%20B/AddOnB-B.pdf

**Comment by zas** [comment]
File was removed by https://github.com/freeDSP/freeDSP-aurora/commit/62fd40cd7139a54ca8f13c47d5be9e3a5f3ebbf2
Was it intentional?

**Comment by cleener** [comment]
[AddOnB-A.pdf](https://github.com/freeDSP/freeDSP-aurora/files/5826653/AddOnB-A.pdf)

**Comment by dspverden** [comment]
Updated schematic PDFs here: 70e72e3
