### ISSUE TITLE
Documentation: User Manual EN 2.1.0: page 6, obsolete paragraph

### ISSUE THREAD

**Issue by zas** [freeDSP/freeDSP-aurora#48]
_As part of the project the open source software **auverdionControl** is published that controls the operation of the freeDSP-aurora from macOS, Windows or iOS. Via the control software the user can access all parameters of the uploaded DSP plugin. Due to the open source licenses users can modify the control software for supporting their own DSP plugins._

**Comment by dspverden** [comment]
Fixed: 89b92949f60f382ca76765154c1b1950259f8080
