### ISSUE TITLE
power supply issue

### ISSUE THREAD

**Issue by bob808** [freeDSP/freeDSP-aurora#5]
I see that the DSP/ADC/DAC chips are powered from the single 3.3V supply (IC106), provided by a linear regulator that drops it from 12V.
ADAU1452 can draw 500mA in full program. Just the DSP means the small regulator will have to dissipate 4.3W.
That thing will go like popcorn.
You need a lower voltage on its input, or use a switching regulator. This is in not safe as it is now.
IC107 as well is pretty loaded at the quiescent current of the opamps + analog stages of ADC/DAC. It dissipates 1.5W with no work from the opamps.
This board should be run at max 6-7V as it is now. That should work.

**Comment by dspverden** [comment]
This has been addressed already. Please refer to the documentation.
