### ISSUE TITLE
rk.lib and rkdev.lib are missing from the KiCad project files

### ISSUE THREAD

**Issue by wolfield** [freeDSP/freeDSP-aurora#58]
Since most of the symbols and footprints used in the project are custom made and not from the standard KiCad library, absence of the mentioned library files renders the whole KiCad project very hard to use and almost impossible to work on.

**Comment by dspverden** [comment]
The kicad project comes with a cache.lib that holds all the symbols needed for the project. Used that in stead of rk.lib and rkdev.lib
