### ISSUE TITLE
4FIR: Master Volume slider is at 50% after reboot of aurora

### ISSUE THREAD

**Issue by Finnitio** [freeDSP/freeDSP-aurora#63]
When I reboot the DSP the master volume slider is at 50% which is not the volume i have set up in the plugin.

**Comment by dspverden** [comment]
Did you press Store Preset to make all settings including the Master Volume non-volatile?

**Comment by MarsianCRaute** [comment]
Master volume is stored, slider position is not. When moving for the first time after rebooting it will adjust volume according to position.

**Comment by Finnitio** [comment]
+1

**Comment by dspverden** [comment]
Fixed. 10d50f0
