### ISSUE TITLE
4FIR Plugin Bypass Filter

### ISSUE THREAD

**Issue by MarsianCRaute** [freeDSP/freeDSP-aurora#66]
"Updating..." message stays till refresh/pressing F5 after bypassing a FIR Filter. Impulse response data is removed after reseting bypass. Maybe linked to #60 ?

**Comment by dspverden** [comment]
Should be fixed by 23c243a
Plz update firmware and reinstall plugin for testing

**Comment by MarsianCRaute** [comment]
Will test asap. Hopefully tomorrow.

**Comment by Finnitio** [comment]
I tested it and it works to bypass and reenable the fir filter.

**Comment by MarsianCRaute** [comment]
Confirmed.
