### ISSUE TITLE
4FIR Plugin Input Selection visual reset to Analog1

### ISSUE THREAD

**Issue by MarsianCRaute** [freeDSP/freeDSP-aurora#67]
Input selection is stored, but after reopening browser (FF, cookies cleared) it displays Analog1 for all channels. All selection are still correct, but not displayed correctly.
<img width="346" alt="2020-11-02 16_34_53-AURORA DSP" src="https://user-images.githubusercontent.com/73755631/97887108-bc015280-1d29-11eb-9965-82df5f7638be.png">

**Comment by dspverden** [comment]
Can you show me the version numbers at the right bottom?

**Comment by MarsianCRaute** [comment]
<img width="141" alt="2020-11-02 16_59_12-AURORA DSP" src="https://user-images.githubusercontent.com/73755631/97889533-c113d100-1d2c-11eb-8b58-4e26f9f5f39a.png">
Should be 10d50f0 ...

**Comment by dspverden** [comment]
Did you recompile the firmware from the develop branch? Seems that your FW is outdated.

**Comment by MarsianCRaute** [comment]
I'm a simple man - I download things, upload things and complain when stuff isn't working.
What needs to be recompiled? I thought using the WebApp folder from develop is enough.

**Comment by dspverden** [comment]
recompile aurora.ino

**Comment by MarsianCRaute** [comment]
ESPAsyncWebServer.h: No such file or directory
ufff

**Comment by dspverden** [comment]
You did read the build instructions? Anyway, I have just compiled it for you.
[aurora.ino.esp32.bin.zip](https://github.com/freeDSP/freeDSP-aurora/files/5476699/aurora.ino.esp32.bin.zip)

**Comment by MarsianCRaute** [comment]
Pls forgive a n00b...
Case closed.
