### ISSUE TITLE
Apple Remote IR commands

### ISSUE THREAD

**Issue by MikaRau** [freeDSP/freeDSP-aurora#73]
It seems that Apple's commands depend where you live? Atleast here in Finland default arduino code didn't work. 
Here are commands after sniffing them for finnish(?) users:
Up:	 77E150F7
Down:	77E130F7
Left:	77E190F7
Right:	77E160F7
Middle:	77E1A0F7
Menu:	77E1C0F7
Play:	77E1FAF7

**Comment by zas** [comment]
It should be solved by https://github.com/freeDSP/freeDSP-aurora/pull/97
Is it possible for you to test and confirm?

**Comment by MikaRau** [comment]
> It should be solved by #97 Is it possible for you to test and confirm?

I will test it once I get my amp/dsp combo back up and running (couple of weeks till I get my parts). Your solution seems really interesting.

**Comment by dspverden** [comment]
For Apple remotes it should be fixed by this commit: 67fe23e
