### ISSUE TITLE
Persisting phase correction bypass [2.1.3. alpha 1]

### ISSUE THREAD

**Issue by OldKamuffel** [freeDSP/freeDSP-aurora#74]
Activating the bypass on the phase correction will not be saved on 'Store Preset'. 
After switching to another preset and back the bypass configuration is lost.
Also after export and reimport a preset.
Other values (hz and Q) are saved correctly.

Saw on:
Fw 2.1.3 (alpha 1)
Gui: 2.1.3
Plugin: 8 Channel and 7.1
Addon: Balanced Live
Windows, Chrome Browser

**Comment by dspverden** [comment]
Fixed by 9410e82
