### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by artpelling** [freeDSP/freeDSP-aurora#85]
IMHO the documentation for this project in its current state is not very thorough. It covers the basics, but makes it tedious to dive deeper into it. A lot of the times it feels like "reinventing the wheel" when trying to understand and change the source code or make new breakout boards. It is frustrating to constantly run into problems that somebody else has surely already found a solution for.
A community driven documentation page, where knowledge can be pooled publicly would help with this issue. I suggest to use the Wiki page here on github for that reason.
This would significantly help community building, making the project more attractive in general an would also drastically improve the experience for new users.

The impression I get from the project so far is that there the devs are busy with maintenance and bugfixes for "consumer level" users and resources for higher level support and development of new features are lacking. There is a discord channel with a few users, other than that there is a lot of discussion on the diy-hifi-forum which is only in German, has a closed registration and the overall quality of communication seems very inefficient there.

Providing a central place for a thorough documentation of custom builds and features users have implemented would also benefit the maintainers of this repo as a lot of question could be already answered here. Personally, I would be happy to write small tutorials/howtos of the solutions I found for several issues I have encountered.

Related to #23

**Comment by dspverden** [comment]
I like the wiki idea. I just enabled that feature, so nothing is there, yet, but feel free to add pages. I have made the wiki "public". Everyone with a GitHub account can contribute the wiki now.
