### ISSUE TITLE
Double include of display.h

### ISSUE THREAD

**Issue by exislow** [freeDSP/freeDSP-aurora#88]
I have noticed that this line is present twice:

`#include "display.h"`
https://github.com/freeDSP/freeDSP-aurora/blob/master/SOURCES/WEBAPP/ESP32/aurora/aurora.ino#L30
https://github.com/freeDSP/freeDSP-aurora/blob/master/SOURCES/WEBAPP/ESP32/aurora/aurora.ino#L33

What is the reason for that? Or is this just a suspect to refactoring?

**Comment by dspverden** [comment]
Fixed: 049db8c4606b28c6274ccfad7ccbaad103a1ba79
