### ISSUE TITLE
v2.2.0: USBin not working

### ISSUE THREAD

**Issue by MarsianCRaute** [freeDSP/freeDSP-aurora#91]
USB in is not working, tested both 4FIR and 8 channels. No sound, but connection shown in Win 10 20H2. Analog in/out works fine.
Back to 2.1.4, USB works as it should.

Will check the new plugin templates later, maybe something missing?

**Comment by dspverden** [comment]
I think I have fixed it. It was a bug in the new python script. Please reload the release from the release page. I was too lazy to make a new subversion for this...

**Comment by MarsianCRaute** [comment]
Will test asap, thx!

**Comment by MarsianCRaute** [comment]
Fixed!
